import 'https://code.jquery.com/jquery-3.6.4.min.js';
import 'https://code.jquery.com/jquery-migrate-1.2.1.min.js';
import 'https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js';
import './slider';
import './slider-reviews.js';
import './slider-modal.js';
import './modal.js';
import './mobile-menu.js';
import './no-active-link.js';
